version: '3'
services:

  laravel:
    container_name: laravel
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERID=1000
    command: ["php", "artisan", "serve", "--host", "0.0.0.0", "--port", "8000"]
# php artisan serve --host=0.0.0.0 --port=80
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg!password
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@lbaw.com
      PGADMIN_DEFAULT_PASSWORD: pg!password
    ports:
      - "4321:80"
    depends_on:
      - postgres
